In [2]:
import numpy as np

In [3]:
import pandas as pd

Data cleaning and preprocessing

In [4]:
df=pd.read_csv("CWC2023.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match ID          48 non-null     int64
 1   Match Date        48 non-null     str
 2   Match Time        48 non-null     str
 3   City              48 non-null     str
 4   Stadium           48 non-null     str
 5   Team A            48 non-null     str
 6   Team B            48 non-null     str
 7   Toss Winner       48 non-null     str
 8   Toss Decision     48 non-null     str
 9   Score A           48 non-null     int64
 10  Wickets A         48 non-null     int64
 11  Overs Played A    48 non-null     float64
 12  Maiden Overs A    48 non-null     int64
 13  Boundaries A      48 non-null     int64
 14  Runrate A         48 non-null     float64
 15  Unnamed: 15       0 non-null      float64
 16  Unnamed: 16       0 non-null      float64
 17  Unnamed: 17       0 non-null      float64
 18  Unnamed: 18       0 non-null      float64
 19  Extras A          48 non-null     int64
 20  Score B           48 non-null     int64
 21  Wickets B         48 non-null     int64
 22  Overs Played B    48 non-null     float64
 23  Maiden Overs B    48 non-null     int64
 24  Unnamed: 24       0 non-null      float64
 25  Unnamed: 25       0 non-null      float64
 26  Boundaries B      48 non-null     int64
 27  Runrate B         48 non-null     str
 28  Unnamed: 28       0 non-null      float64
 29  Unnamed: 29       0 non-null      float64
 30  Unnamed: 30       0 non-null      float64
 31  Unnamed: 31       0 non-null      float64
 32  Unnamed: 32       0 non-null      float64
 33  Extras B          48 non-null     int64
 34  Wining Team       48 non-null     str
 35  Margin            48 non-null     str
 36  Man of the Match  48 non-null     str
dtypes: float64(14), int64(11), str(12)
memory usage: 14.0 KB

In [6]:
df.isnull()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,Runrate B,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Extras B,Wining Team,Margin,Man of the Match
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,False,False,False,False

In [7]:
df.isnull().sum()

Match ID             0
Match Date           0
Match Time           0
City                 0
Stadium              0
Team A               0
Team B               0
Toss Winner          0
Toss Decision        0
Score A              0
Wickets A            0
Overs Played A       0
Maiden Overs A       0
Boundaries A         0
Runrate A            0
Unnamed: 15         48
Unnamed: 16         48
Unnamed: 17         48
Unnamed: 18         48
Extras A             0
Score B              0
Wickets B            0
Overs Played B       0
Maiden Overs B       0
Unnamed: 24         48
Unnamed: 25         48
Boundaries B         0
Runrate B            0
Unnamed: 28         48
Unnamed: 29         48
Unnamed: 30         48
Unnamed: 31         48
Unnamed: 32         48
Extras B             0
Wining Team          0
Margin               0
Man of the Match     0
dtype: int64

In [8]:
df.columns

Index(['Match ID', 'Match Date', 'Match Time', 'City', 'Stadium', 'Team A',
       'Team B', 'Toss Winner', 'Toss Decision', 'Score A', 'Wickets A',
       'Overs Played A', 'Maiden Overs A', 'Boundaries A', 'Runrate A',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Extras A',
       'Score B', 'Wickets B', 'Overs Played B', 'Maiden Overs B',
       'Unnamed: 24', 'Unnamed: 25', 'Boundaries B', 'Runrate B',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Extras B', 'Wining Team', 'Margin', 'Man of the Match'],
      dtype='str')

In [9]:
df.drop(columns=["Unnamed: 15","Unnamed: 16","Unnamed: 17","Unnamed: 18","Unnamed: 24"], inplace=True)

In [10]:
df.isnull().sum()

Match ID             0
Match Date           0
Match Time           0
City                 0
Stadium              0
Team A               0
Team B               0
Toss Winner          0
Toss Decision        0
Score A              0
Wickets A            0
Overs Played A       0
Maiden Overs A       0
Boundaries A         0
Runrate A            0
Extras A             0
Score B              0
Wickets B            0
Overs Played B       0
Maiden Overs B       0
Unnamed: 25         48
Boundaries B         0
Runrate B            0
Unnamed: 28         48
Unnamed: 29         48
Unnamed: 30         48
Unnamed: 31         48
Unnamed: 32         48
Extras B             0
Wining Team          0
Margin               0
Man of the Match     0
dtype: int64

In [11]:
df.drop(columns=["Unnamed: 25","Unnamed: 28","Unnamed: 29","Unnamed: 30","Unnamed: 31","Unnamed: 32"], inplace=True)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match ID          48 non-null     int64
 1   Match Date        48 non-null     str
 2   Match Time        48 non-null     str
 3   City              48 non-null     str
 4   Stadium           48 non-null     str
 5   Team A            48 non-null     str
 6   Team B            48 non-null     str
 7   Toss Winner       48 non-null     str
 8   Toss Decision     48 non-null     str
 9   Score A           48 non-null     int64
 10  Wickets A         48 non-null     int64
 11  Overs Played A    48 non-null     float64
 12  Maiden Overs A    48 non-null     int64
 13  Boundaries A      48 non-null     int64
 14  Runrate A         48 non-null     float64
 15  Extras A          48 non-null     int64
 16  Score B           48 non-null     int64
 17  Wickets B         48 non-null     int64
 18  Overs Played B    48 non-null     float64
 19  Maiden Overs B    48 non-null     int64
 20  Boundaries B      48 non-null     int64
 21  Runrate B         48 non-null     str
 22  Extras B          48 non-null     int64
 23  Wining Team       48 non-null     str
 24  Margin            48 non-null     str
 25  Man of the Match  48 non-null     str
dtypes: float64(3), int64(11), str(12)
memory usage: 9.9 KB

In [13]:
df.shape

(48, 26)

In [14]:
df.isnull().sum()

Match ID            0
Match Date          0
Match Time          0
City                0
Stadium             0
Team A              0
Team B              0
Toss Winner         0
Toss Decision       0
Score A             0
Wickets A           0
Overs Played A      0
Maiden Overs A      0
Boundaries A        0
Runrate A           0
Extras A            0
Score B             0
Wickets B           0
Overs Played B      0
Maiden Overs B      0
Boundaries B        0
Runrate B           0
Extras B            0
Wining Team         0
Margin              0
Man of the Match    0
dtype: int64

In [15]:
df.head()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,Score B,Wickets B,Overs Played B,Maiden Overs B,Boundaries B,Runrate B,Extras B,Wining Team,Margin,Man of the Match
0,1,05-10-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,England,NewZealand,NewZealand,Field,282,...,283,1,36.2,2,38,7.78,6,NewZealand,9 Wickets,Rachin Ravindra
1,2,06-10-2023,2:00 PM,Hyderabad,Eden Gardens,Pakistan,Netherlands,Netherlands,Field,286,...,205,10,41.0,1,24,5,9,Pakistan,81 Runs,Saud Shakeel
2,3,07-10-2023,2:00 PM,Dharamshala,HPCA Stadium,Afghanistan,Bangladesh,Bangladesh,Field,156,...,158,4,34.4,5,14,4.55,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz
3,4,07-10-2023,2:00 PM,Delhi,Arun Jaitley Stadium,South Africa,Sri Lanka,Sri Lanka,Field,428,...,326,10,44.5,1,48,7.27,23,South Africa,102 Runs,Aiden Markram
4,5,08-10-2023,2:00 PM,Chennai,M. A. Chidambaram Stadium,Australia,India,Australia,Bat,199,...,201,4,41.2,4,17,4.86,12,India,6 wickets,KL Rahul

In [16]:
df.tail()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,Score B,Wickets B,Overs Played B,Maiden Overs B,Boundaries B,Runrate B,Extras B,Wining Team,Margin,Man of the Match
43,44,11-11-2023,2:00 PM,Kolkata,Eden Gardens,England,Pakistan,England,Bat,244,...,337,9,43.3,0,43,5.6,6,England,93 Runs,David Willey
44,45,12-11-2023,2:00 PM,Bangalore,M. Chinnaswamy Stadium,India,Netherlands,India,Bat,410,...,250,10,47.5,0,28,5.22,15,India,160 Runs,Shreyas Iyer
45,46,15-11-2023,2:00 PM,Mumbai,Wankhede Stadium,India,NewZealand,India,Bat,397,...,327,10,48.5,1,40,6.69,8,India,70 Runs,Mohammed Shami
46,47,16-11-2023,2:00 PM,Kolkata,Eden Gardens,Australia,South Africa,South Africa,Bat,215,...,212,10,49.4,1,24,4.26,17,Australia,3 Wickets,Travis Head
47,48,19-11-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,India,Australia,Australia,Field,240,...,241,4,43.0,0,27,5.6,12,Australia,6 Wickets,Travis Head

In [17]:
df.duplicated().sum()

np.int64(0)

Business questions

In [18]:
#Question 1: Which team has the highest number of wins in the tournament?
df["Wining Team"]

0       NewZealand
1         Pakistan
2       Bangladesh
3     South Africa
4            India
5       NewZealand
6          England
7         Pakistan
8            India
9     South Africa
10      NewZealand
11           India
12     Afghanistan
13       Australia
14     Netherlands
15      NewZealand
16           India
17       Australia
18       Sri Lanka
19    South Africa
20           India
21     Afghanistan
22    South Africa
23       Australia
24       Sri Lanka
25    South Africa
26       Australia
27     Netherlands
28           India
29     Afghanistan
30        Pakistan
31    South Africa
32           India
33     Afghanistan
34        Pakistan
35       Australia
36           India
37      Bangladesh
38       Australia
39         England
40      NewZealand
41    South Africa
42       Australia
43         England
44           India
45           India
46       Australia
47       Australia
Name: Wining Team, dtype: str

In [19]:
df.rename(columns={"Wining Team":"Winning Team"}, inplace=True)

In [20]:
df["Winning Team"].value_counts().head(1)
#Ans 1: India has the highes number of wins.

Winning Team
India    10
Name: count, dtype: int64

In [21]:
#Questions 2: Which team has won most tosses?
df["Toss Winner"].value_counts().head(1)
#Ans 2: England won the most number of tosses in the tournament.

Toss Winner
England    7
Name: count, dtype: int64

In [22]:
#Question 3: Which venue hosted most of the matches?
df["Stadium"].value_counts().head(1)
#Ans 3: Eden gardens

Stadium
Eden Gardens    6
Name: count, dtype: int64

In [23]:
#Question 4: Which team scored the highest total?
df["Score A"].sort_values(ascending=False).head(1)

3    428
Name: Score A, dtype: int64

In [24]:
df["Score B"].sort_values(ascending=False).head(1)

26    383
Name: Score B, dtype: int64

In [25]:
df.loc[df["Score A"]==428, "Team A"]
#Ans 4: South Africa scored the highest runs

3    South Africa
Name: Team A, dtype: str

In [26]:
#Question 5: Which team conceeded the highest runs?
#Note, we can directly get the row of the team which has scored highest total and the other team would be the ans. But by coding:
df.loc[df["Score A"]==428, "Team B"]
#Ans 5: Sri Lanka conceeded the highest runs.

3    Sri Lanka
Name: Team B, dtype: str

In [27]:
pd.set_option("display.max_columns", None)

In [28]:
df.head()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,Wickets A,Overs Played A,Maiden Overs A,Boundaries A,Runrate A,Extras A,Score B,Wickets B,Overs Played B,Maiden Overs B,Boundaries B,Runrate B,Extras B,Winning Team,Margin,Man of the Match
0,1,05-10-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,England,NewZealand,NewZealand,Field,282,9,50.0,2,27,5.64,8,283,1,36.2,2,38,7.78,6,NewZealand,9 Wickets,Rachin Ravindra
1,2,06-10-2023,2:00 PM,Hyderabad,Eden Gardens,Pakistan,Netherlands,Netherlands,Field,286,10,49.0,1,36,5.83,9,205,10,41.0,1,24,5,9,Pakistan,81 Runs,Saud Shakeel
2,3,07-10-2023,2:00 PM,Dharamshala,HPCA Stadium,Afghanistan,Bangladesh,Bangladesh,Field,156,10,37.2,1,17,4.17,8,158,4,34.4,5,14,4.55,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz
3,4,07-10-2023,2:00 PM,Delhi,Arun Jaitley Stadium,South Africa,Sri Lanka,Sri Lanka,Field,428,5,50.0,1,59,8.56,20,326,10,44.5,1,48,7.27,23,South Africa,102 Runs,Aiden Markram
4,5,08-10-2023,2:00 PM,Chennai,M. A. Chidambaram Stadium,Australia,India,Australia,Bat,199,10,49.3,1,18,4.02,8,201,4,41.2,4,17,4.86,12,India,6 wickets,KL Rahul

In [ ]:
#Question 6: Who has won highest number of man of the match award?
df["Man of the Match"].value_counts(ascending=False).head(1)
#Ans 6: Md. Shami has won highest number of man of the match award.

Man of the Match
Mohammed Shami    3
Name: count, dtype: int64

In [ ]:
#Question 7: Which team had the highest number of boundaries in a match?
df["Boundaries A"].sort_values(ascending=False).head(1)

3    59
Name: Boundaries A, dtype: int64

In [31]:
df["Boundaries B"].sort_values(ascending=False).head(1)

3    48
Name: Boundaries B, dtype: int64

In [ ]:
df.loc[df["Boundaries A"]==59, "Team A"]
#Ans 7: South Africa had the highest number of boundaries

3    South Africa
Name: Team A, dtype: str

In [ ]:
#Question 8: Which match had the highes total score
df1=df["Score A"]+df["Score B"]
df1

0     565
1     491
2     314
3     754
4     400
5     545
6     591
7     689
8     545
9     488
10    493
11    383
12    499
13    424
14    452
15    427
16    517
17    672
18    525
19    569
20    547
21    568
22    615
23    489
24    316
25    541
26    771
27    371
28    358
29    483
30    409
31    524
32    412
33    360
34    601
35    539
36    409
37    561
38    584
39    518
40    343
41    491
42    613
43    581
44    660
45    724
46    427
47    481
dtype: int64

In [34]:
df1.sort_values(ascending=False).head(1)

26    771
dtype: int64

In [ ]:
df.loc[26,"Match ID"]
#Ans 8: Match number 27 had the highest score, 771 runs.

np.int64(27)

In [ ]:
#Question 9:Which match had the highest number of extras?
df2=df["Extras A"]+df["Extras B"]

In [50]:
df2.sort_values(ascending=False).head(1)

18    57
dtype: int64

In [ ]:
df.loc[18, "Match ID"]
#Ans 9: Match number 19 had the highest number of combined extras

np.int64(19)

In [ ]:
#Question 10: After winning the toss, which decision did the teams prefer more?
df["Toss Decision"].value_counts()
#Ans 10: Teams preffered fielding more, after winning the toss

Toss Decision
Field    26
Bat      22
Name: count, dtype: int64

In [ ]:
#Question 11: Which team faced the least overs in the tournament?
df["Overs Played A"].sort_values().head(1)

33    31.3
Name: Overs Played A, dtype: float64

In [41]:
df["Overs Played B"].sort_values().head(1)

32    19.4
Name: Overs Played B, dtype: float64

In [49]:
df.loc[32, ["Team A", "Team B", "Overs Played A", "Overs Played B"]]
#Ans 11: Sri Lanka faced the least number of overs.

Team A                India
Team B            Sri Lanka
Overs Played A         50.0
Overs Played B         19.4
Name: 32, dtype: object

In [ ]:
#Question 12: What percentage of matches were won by the team that won the toss?
toss_win_won=df["Toss Winner"]==df["Winning Team"]
toss_win_won.sum()

np.int64(19)

In [ ]:
p=(toss_win_won.sum()/len(df))*100
p
#Ans 12: 39.583%

np.float64(39.58333333333333)